language: node_js

node_js:
  - '6'
  - '9'

sudo: required

before_install:
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xvzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make
  - cd ..
  - cmake --version

install:
  - npm install

  # install opencv4nodejs and run tests
  - git clone https://github.com/justadudewhohacks/opencv4nodejs
  - cd opencv4nodejs
  # uninstall npm version of opencv-build
  - npm uninstall opencv-build
  # install new opencv-build version
  - npm install ../
  - npm install
  - cd test
  - npm install
  - npm run test-docker

